### ISSUE TITLE
Error in installing

### ISSUE THREAD

**Issue by sleepypioneer** [barrachri/berlin-jobs#1]
Hi I have installed Aconda following the instructions but having a problem with this command:

conda env create -n pandas-pyladies -f environment.yml

Its saying ResolvePackageNotFound:
- appnope 0.1.0 py36_0

Any help appreciated.
MfG

Jessica

![error](https://user-images.githubusercontent.com/23617373/33039241-8d8c093e-ce37-11e7-8511-3dcbe0caaae3.PNG)

**Comment by barrachri** [comment]
Hi @sleepypioneer, can you open `environment.yml` on your machine and remove this line (https://github.com/barrachri/berlin-jobs/blob/master/environment.yml#L6)?

If you get more errors like this you have to repeat the process with the other libraries.

**Comment by sleepypioneer** [comment]
Hi @barrachri 

Many thanks for the advice, it's throwing up quite a few but I'm working through them. Will have to continue later today, and hopefully get it going before this evening. 

Best wishes.

**Comment by sleepypioneer** [comment]
Got throught them but it still doesn't want to play nice :( Now I'm getting the following message. I should have done this earlier, apologies.
![seconderror](https://user-images.githubusercontent.com/23617373/33083106-c4b32508-cede-11e7-9a5d-5921063f0a65.PNG)

**Comment by barrachri** [comment]
@sleepypioneer no problems, try to be a little bit earlier at the meetup and I'll try to help you there.

**Comment by MisterRios** [comment]
@sleepypioneer @barrachri :
 I had the same issues with setup- Here's how I got it working 
I went into `environment.yml` and deleted the en-core-web-sm line
If you try to activate conda here, it gives you an error.
Then I had to re-install the environment, so I had to do a `rm -rf ~/miniconda3/envs/pandas-pyladies`
and then re-run `conda env create -n pandas-pyladies -f environment.yml`
then activate and download the spacy libraries.

**Comment by sleepypioneer** [comment]
Thanks @MisterRios I will try that quick now from home and then get over to the Meet up @barrachri before the meetup. Many thanks to you both, much appreciated!!
